project:
  directory: /home/eduard/Privat/R3P/room_control

web:
  domain:       room.local
  bind:         "127.0.0.1:4443"
  cert_path:    config/cert.pem
  cert_subject: "/C=DE/ST=Lower Saxony/L=My City/O=My Organization/OU=Service/CN=$domain/emailAddress=person@example.org"

room:

  defaults:
    position_min:    0 # closed
    position_max:  100 # open
    opener_speed:   10 # 10 % per second
    shadow_speed:   10 # 10 % per second

  windows:
    count:         8

  window_0:
    id:             win_l1
    name:           "links 1 (1. von vorne)"
    opener_on_bit:  0
    opener_dir_bit: 1
    shadow_on_bit:  3
    shadow_dir_bit: 4
  window_1:
    id:             win_l2
    name:           "links 2 (2. von vorne)"
    opener_on_bit:  5
    opener_dir_bit: 6
    shadow_on_bit:  7
    shadow_dir_bit: 8
  window_2:
    id:             win_l3
    name:           "links 3 (3. von vorne)"
    opener_on_bit:  9
    opener_dir_bit: 10
    shadow_on_bit:  11
    shadow_dir_bit: 12
  window_3:
    id:             win_l4
    name:           "links 4 (4. von vorne)"
    opener_on_bit:  13
    opener_dir_bit: 14
    shadow_on_bit:  15
    shadow_dir_bit: 16
  window_4:
    id:             win_r1
    name:           "rechts 1 (1. von vorne)"
    opener_on_bit:  17
    opener_dir_bit: 18
    shadow_on_bit:  19
    shadow_dir_bit: 20
  window_5:
    id:             win_r2
    name:           "rechts 2 (2. von vorne)"
    opener_linked:  win_r1
    shadow_linked:  win_r1
  window_6:
    id:             win_r3
    name:           "rechts 3 (3. von vorne)"
    opener_on_bit:  21
    opener_dir_bit: 22
    shadow_on_bit:  23
    shadow_dir_bit: 24
  window_7:
    id:             win_r4
    name:           "rechts 4 (4. von vorne)"
    opener_linked:  win_r3
    shadow_linked:  win_r3

  dimmer:
    count: 1
  dimmer_1:
    id:             dim_0
    voltage:        230    # voltage of the connection
    voltage_min:    60     # voltage for minimal power, for power below this the current is switched off
    voltage_max:    230    # voltage for maximal power
    curve:          linear
