project:
  directory: /home/eduard/Privat/R3P/room_control # project base directory 

web:
  domain:       room.local    # domainname
  
  # list of ip addresses to bind to, tls: prefix for https, ipv6 enclosed in "[]"
  bind:         "127.0.1.2:4080,tls:127.0.1.2:4443" # default: "localhost:8080"
  
  # TLS handling:
  # To handle https requests the cert_path has to be specified.
  # The cert_subject is used to install a selfsigned certificate.
  cert_path:    config/cert.pem  # tls certificate file for https
  cert_subject: "/C=DE/ST=Lower Saxony/L=My City/O=My Organization/OU=Service/CN=$domain/emailAddress=person@example.org"

room:

  shift_register:      # hardware configuration
    pinDATA:    7      # pin  7 = GPIO4
    pinCLOCK:  11      # pin 11 = GPIO17
    pinLATCH:  13      # pin 13 = GPIO27
    pinENABLE: 15      # pin 15 = GPIO22
    bits:      48      # number of bits in the shift register, default is 16

    # Signal level to output a 0 or a 1:
    enabledLevel: HIGH # level of enable pin if enabled HIGH or LOW, default is HIGH
    dataLevel:    HIGH # level of data pin for a 1, HIGH or LOW, default is HIGH

    # Signal timing: negative value means no no time to wait, positive float values mean time to wait in seconds 
    setupTime:      -1 # time need to set up the data signal before clock rising edge, default -1
    holdTime:       -1 # time need to hold the data signal after clock rising edge, default -1
    clockTime:      -1 # time need between two shifts, default -1

  defaults:            # defaults for the room window configuration
    opener:            # window opener data
      position_min:     0.0 # closed
      position_max:   100.0 # open
      speed_dir0:       5.0 # % per second, speed to open the window
      speed_dir1:       5.0 # % per second, speed to close the window
      hard_pos_min:   -10.0 # hard motor position to close from pos_min to hard min end motor position
      hard_pos_max:   110.0 # hard motor position to close from pos_max to hard max end motor position
      slip:             3.0 # difference of position when moved from different directions to a hard_pos
      drift:           0.01 # position difference (uncertenty) per moved position 
    blind:             # roller blind data
      position_min:     0.0 # closed
      position_max:   100.0 # open
      speed_dir0:       5.0 # pos units per second, speed to open the window
      speed_dir1:       5.0 # pos units per second, speed to close the window
      hard_pos_min:   -10.0 # hard motor position to close from pos_min to hard min end motor position
      hard_pos_max:   110.0 # hard motor position to close from pos_max to hard max end motor position
      slip:             3.0 # difference of position when moved from different directions to a hard_pos
      drift:           0.01 # position difference (uncertenty) per moved position 
      # 
      turn_pos_diff:   10.0 # position difference to turn the blind slat
      angle_min:        0.0 # fully open slat 
      angle_max:      100.0 # fully closed slat    

  windows:
    count:         6

  window_0:
    id:             L1
    name:           "links 1 (1. von vorne)"
    opener:
      on_bit:  0
      dir_bit: 1
    blind:
      on_bit:  2
      dir_bit: 3

  window_1:
    id:             L2
    name:           "links 2 (2. von vorne)"
    opener:
      on_bit:  4
      dir_bit: 5
    blind:
      on_bit:  6
      dir_bit: 7
      
  window_2:
    id:             L3
    name:           "links 3 (3. von vorne)"
    opener:
      on_bit:   8
      dir_bit:  9
    blind:
      on_bit:  10
      dir_bit: 11
      
  window_3:
    id:             L4
    name:           "links hinten (4. und 5. von vorne)"
    opener:
      on_bit:  12
      dir_bit: 13
    blind:
      on_bit:  14
      dir_bit: 15

  window_4:
    id:             R1
    name:           "rechts vorne (1. und 2. von vorne)"
    opener:
      on_bit:  16
      dir_bit: 17
    blind:
      on_bit:  18
      dir_bit: 19
    
  window_5:
    id:             R4
    name:           "rechts hinten (3. und 4. von vorne)"
    opener:
      on_bit:  20
      dir_bit: 21
    blind:
      on_bit:  22
      dir_bit: 23

  dimmer:
    count: 1
  dimmer_1:
    id:             dim_0
    voltage:        230    # voltage of the connection
    voltage_min:    60     # voltage for minimal power, for power below this the current is switched off
    voltage_max:    230    # voltage for maximal power
    curve:          linear
